spring:
  application:
    name: web
  devtools:
    livereload:
      enabled: true
  boot:
    admin:
      url: http://localhost:9090


server:
  port: 8080

management:
  security:
    enabled: false

logging:
  path: "log"

info:
  source: http://alm.dams.com:8080/gitblit
  build: http://alm.dams.com:8080/jenknis
  profile: ${spring.profile.active}